import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { requireAdmin } from '@/lib/middleware/roleCheck'
import { createAuditLog, getRequestMetadata } from '@/lib/auditLog'

// GET - Fetch company settings (returns first company or creates default)
export async function GET() {
  try {
    let company = await prisma.company.findFirst()

    // Create default company if none exists
    if (!company) {
      company = await prisma.company.create({
        data: {
          name: 'Oficio Property Leasing',
          contactPerson: '',
          contactPosition: '',
          address: '',
          emails: ['info@oficiopl.com'],
          mobiles: [],
          telephone: null,
          plan: 'Virtual',
          signers: [],
        },
      })
    }

    return NextResponse.json({ success: true, data: company })
  } catch (error) {
    console.error('Error fetching company:', error)
    return NextResponse.json(
      { success: false, error: 'Failed to fetch company settings' },
      { status: 500 }
    )
  }
}

// PUT - Update company settings — Admin only
export async function PUT(request: NextRequest) {
  try {
    const auth = await requireAdmin()
    if (auth.error || !auth.user) {
      return NextResponse.json({ success: false, error: auth.error || 'Unauthorized' }, { status: auth.status || 401 })
    }
    const user = auth.user

    const body = await request.json()

    // Validate string lengths
    if (body.name && String(body.name).length > 200) {
      return NextResponse.json({ success: false, error: 'Company name too long (max 200)' }, { status: 400 })
    }
    if (body.address && String(body.address).length > 500) {
      return NextResponse.json({ success: false, error: 'Address too long (max 500)' }, { status: 400 })
    }
    if (Array.isArray(body.emails) && body.emails.length > 10) {
      return NextResponse.json({ success: false, error: 'Maximum 10 email addresses' }, { status: 400 })
    }
    if (Array.isArray(body.mobiles) && body.mobiles.length > 10) {
      return NextResponse.json({ success: false, error: 'Maximum 10 mobile numbers' }, { status: 400 })
    }

    // Get existing company or create if not exists
    let company = await prisma.company.findFirst()
    const oldData = company ? { name: company.name, address: company.address, contactPerson: company.contactPerson } : undefined

    const companyData: Record<string, unknown> = {
      name: body.name,
      contactPerson: body.contactPerson,
      contactPosition: body.contactPosition,
      address: body.address,
      emails: body.emails || [],
      mobiles: body.mobiles || [],
      telephone: body.telephone || null,
      plan: body.plan,
      signers: body.signers || [],
    }

    // Include automation fields if provided
    if (body.autoGenerateInvoices !== undefined) {
      companyData.autoGenerateInvoices = Boolean(body.autoGenerateInvoices)
    }
    if (body.autoGenerateDay !== undefined) {
      companyData.autoGenerateDay = Number(body.autoGenerateDay)
    }
    if (body.autoGenerateDaysAhead !== undefined) {
      companyData.autoGenerateDaysAhead = Number(body.autoGenerateDaysAhead)
    }

    if (company) {
      // Update existing
      company = await prisma.company.update({
        where: { id: company.id },
        data: companyData as any,
      })
    } else {
      // Create new
      company = await prisma.company.create({
        data: companyData as any,
      })
    }

    const metadata = getRequestMetadata(request)
    await createAuditLog({
      userId: user.id,
      userName: user.name || user.email,
      userEmail: user.email,
      userRole: user.role as 'ADMIN' | 'EMPLOYEE',
      action: 'UPDATE',
      actionCategory: 'SETTINGS',
      entityType: 'company',
      entityId: company.id,
      entityName: company.name,
      beforeData: oldData,
      afterData: { name: company.name, address: company.address, contactPerson: company.contactPerson },
      changesSummary: `Updated company settings: ${company.name}`,
      ...metadata
    })

    return NextResponse.json({ success: true, data: company })
  } catch (error) {
    console.error('Error updating company:', error)
    return NextResponse.json(
      { success: false, error: 'Failed to update company settings' },
      { status: 500 }
    )
  }
}
