-- Add auto-generate invoice fields to Company
ALTER TABLE "Company" ADD COLUMN "autoGenerateInvoices" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Company" ADD COLUMN "autoGenerateDay" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Company" ADD COLUMN "autoGenerateDaysAhead" INTEGER NOT NULL DEFAULT 30;
