import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { timingSafeEqual } from 'crypto'

function verifyCronSecret(provided: string | null): boolean {
  const expected = process.env.CRON_SECRET
  if (!provided || !expected) return false
  try {
    return timingSafeEqual(Buffer.from(provided), Buffer.from(expected))
  } catch {
    return false
  }
}

export async function POST(request: NextRequest) {
  // Verify cron secret
  const cronSecret = request.headers.get('x-cron-secret')
  if (!verifyCronSecret(cronSecret)) {
    return NextResponse.json({ success: false, error: 'Unauthorized' }, { status: 401 })
  }

  try {
    // Check if auto-generation is enabled
    const company = await prisma.company.findFirst()
    if (!company || !company.autoGenerateInvoices) {
      return NextResponse.json({ success: true, message: 'Auto-generation disabled' })
    }

    // Check if today is the generation day
    const today = new Date()
    if (today.getDate() !== company.autoGenerateDay) {
      return NextResponse.json({ success: true, message: 'Not generation day' })
    }

    // Find all active clients with active contracts
    const clients = await prisma.client.findMany({
      where: { status: 'active', deletedAt: null },
      include: {
        contracts: {
          where: { status: 'active', deletedAt: null },
          orderBy: { endDate: 'desc' },
          take: 1,
        },
      },
    })

    const results = { generated: 0, skipped: 0, errors: 0 }
    const daysAhead = company.autoGenerateDaysAhead

    for (const client of clients) {
      if (client.contracts.length === 0) {
        results.skipped++
        continue
      }

      try {
        // Determine billing period
        const now = new Date()
        const targetDate = new Date(now)
        targetDate.setDate(targetDate.getDate() + daysAhead)

        // Find the next unbilled period
        const lastInvoice = await prisma.invoice.findFirst({
          where: { clientId: client.id, deletedAt: null },
          orderBy: { billingPeriodEnd: 'desc' },
        })

        let periodStart: Date
        if (lastInvoice) {
          periodStart = new Date(lastInvoice.billingPeriodEnd)
          periodStart.setDate(periodStart.getDate() + 1)
        } else {
          periodStart = new Date(client.startDate)
        }

        // Calculate period end based on billing terms. These strings must match the
        // canonical values used everywhere else (BillingTermsSelect, invoices/generate,
        // clients/upload validator): 'Monthly' | 'Quarterly' | 'Semi-Annual' | 'Annual'.
        let periodEnd = new Date(periodStart)
        if (client.billingTerms === 'Quarterly') {
          periodEnd.setMonth(periodEnd.getMonth() + 3)
        } else if (client.billingTerms === 'Semi-Annual') {
          periodEnd.setMonth(periodEnd.getMonth() + 6)
        } else if (client.billingTerms === 'Annual') {
          periodEnd.setFullYear(periodEnd.getFullYear() + 1)
        } else {
          // Monthly (and any unrecognised term) defaults to a 1-month period.
          periodEnd.setMonth(periodEnd.getMonth() + 1)
        }
        periodEnd.setDate(periodEnd.getDate() - 1)

        // Only generate if the period start is within daysAhead
        if (periodStart > targetDate) {
          results.skipped++
          continue
        }

        // Check for existing invoice for this period
        const existing = await prisma.invoice.findFirst({
          where: {
            clientId: client.id,
            billingPeriodStart: periodStart,
            billingPeriodEnd: periodEnd,
            deletedAt: null,
          },
        })

        if (existing) {
          results.skipped++
          continue
        }

        // Calculate amounts (VAT inclusive/exclusive + optional 5% withholding),
        // matching the canonical logic in invoices/route.ts.
        let baseAmount: number
        let vatAmount: number
        let totalAmount: number
        if (client.vatInclusive) {
          totalAmount = client.rentalRate
          baseAmount = totalAmount / 1.12
          vatAmount = totalAmount - baseAmount
        } else {
          baseAmount = client.rentalRate
          vatAmount = baseAmount * 0.12
          totalAmount = baseAmount + vatAmount
        }
        baseAmount = Math.round(baseAmount * 100) / 100
        vatAmount = Math.round(vatAmount * 100) / 100
        totalAmount = Math.round(totalAmount * 100) / 100

        // Due date: 3 days before the start of the billing period (matches PDF terms)
        const dueDate = new Date(periodStart)
        dueDate.setDate(dueDate.getDate() - 3)

        // Reserve the OFC invoice number and create the invoice atomically to avoid
        // duplicate numbers, mirroring invoices/route.ts.
        await prisma.$transaction(async (tx) => {
          const lastInvoice = await tx.invoice.findFirst({
            orderBy: { invoiceNumber: 'desc' },
            select: { invoiceNumber: true },
          })
          let nextNumber = 219
          if (lastInvoice) {
            const parsed = parseInt(lastInvoice.invoiceNumber.replace('OFC', ''), 10)
            if (!isNaN(parsed)) nextNumber = parsed + 1
          }
          const invoiceNumber = `OFC${String(nextNumber).padStart(8, '0')}`

          await tx.invoice.create({
            data: {
              clientId: client.id,
              invoiceNumber,
              amount: baseAmount,
              vatAmount,
              totalAmount,
              netAmount: totalAmount,
              billingPeriodStart: periodStart,
              billingPeriodEnd: periodEnd,
              dueDate,
              status: 'pending',
            },
          })
        }, { isolationLevel: 'Serializable' })

        results.generated++
      } catch (error) {
        console.error(`Error generating invoice for client ${client.id}:`, error)
        results.errors++
      }
    }

    // Log to audit
    await prisma.auditLog.create({
      data: {
        userId: 'system',
        userName: 'System',
        userEmail: 'system@oficio.app',
        userRole: 'SYSTEM',
        action: 'AUTO_GENERATE_INVOICES',
        actionCategory: 'INVOICE',
        entityType: 'invoice',
        changesSummary: `Auto-generated ${results.generated} invoices, skipped ${results.skipped}, errors ${results.errors}`,
      },
    })

    return NextResponse.json({ success: true, data: results })
  } catch (error) {
    console.error('Cron generate invoices error:', error)
    return NextResponse.json({ success: false, error: 'Internal server error' }, { status: 500 })
  }
}
