import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

export async function POST(request: NextRequest) {
  // Verify cron secret
  const cronSecret = request.headers.get('x-cron-secret')
  if (!cronSecret || cronSecret !== process.env.CRON_SECRET) {
    return NextResponse.json({ success: false, error: 'Unauthorized' }, { status: 401 })
  }

  try {
    // Check if auto-generation is enabled
    const company = await prisma.company.findFirst()
    if (!company || !company.autoGenerateInvoices) {
      return NextResponse.json({ success: true, message: 'Auto-generation disabled' })
    }

    // Check if today is the generation day
    const today = new Date()
    if (today.getDate() !== company.autoGenerateDay) {
      return NextResponse.json({ success: true, message: 'Not generation day' })
    }

    // Find all active clients with active contracts
    const clients = await prisma.client.findMany({
      where: { status: 'active', deletedAt: null },
      include: {
        contracts: {
          where: { status: 'active', deletedAt: null },
          orderBy: { endDate: 'desc' },
          take: 1,
        },
      },
    })

    const results = { generated: 0, skipped: 0, errors: 0 }
    const daysAhead = company.autoGenerateDaysAhead

    for (const client of clients) {
      if (client.contracts.length === 0) {
        results.skipped++
        continue
      }

      try {
        // Determine billing period
        const now = new Date()
        const targetDate = new Date(now)
        targetDate.setDate(targetDate.getDate() + daysAhead)

        // Find the next unbilled period
        const lastInvoice = await prisma.invoice.findFirst({
          where: { clientId: client.id, deletedAt: null },
          orderBy: { billingPeriodEnd: 'desc' },
        })

        let periodStart: Date
        if (lastInvoice) {
          periodStart = new Date(lastInvoice.billingPeriodEnd)
          periodStart.setDate(periodStart.getDate() + 1)
        } else {
          periodStart = new Date(client.startDate)
        }

        // Calculate period end based on billing terms
        let periodEnd = new Date(periodStart)
        if (client.billingTerms === 'Monthly') {
          periodEnd.setMonth(periodEnd.getMonth() + 1)
          periodEnd.setDate(periodEnd.getDate() - 1)
        } else if (client.billingTerms === 'Quarterly') {
          periodEnd.setMonth(periodEnd.getMonth() + 3)
          periodEnd.setDate(periodEnd.getDate() - 1)
        } else if (client.billingTerms === 'Semi-Annually') {
          periodEnd.setMonth(periodEnd.getMonth() + 6)
          periodEnd.setDate(periodEnd.getDate() - 1)
        } else if (client.billingTerms === 'Annually') {
          periodEnd.setFullYear(periodEnd.getFullYear() + 1)
          periodEnd.setDate(periodEnd.getDate() - 1)
        } else {
          // Monthly as default
          periodEnd.setMonth(periodEnd.getMonth() + 1)
          periodEnd.setDate(periodEnd.getDate() - 1)
        }

        // Only generate if the period start is within daysAhead
        if (periodStart > targetDate) {
          results.skipped++
          continue
        }

        // Check for existing invoice for this period
        const existing = await prisma.invoice.findFirst({
          where: {
            clientId: client.id,
            billingPeriodStart: periodStart,
            billingPeriodEnd: periodEnd,
            deletedAt: null,
          },
        })

        if (existing) {
          results.skipped++
          continue
        }

        // Generate invoice number
        const lastNumber = await prisma.invoice.findFirst({
          orderBy: { invoiceNumber: 'desc' },
        })
        const nextNum = lastNumber
          ? String(parseInt(lastNumber.invoiceNumber.replace(/\D/g, '')) + 1).padStart(6, '0')
          : '000001'
        const invoiceNumber = `INV-${nextNum}`

        // Calculate amounts
        const amount = client.rentalRate
        const vatAmount = client.vatInclusive ? 0 : amount * 0.12
        const totalAmount = amount + vatAmount

        // Due date: 15 days after period start
        const dueDate = new Date(periodStart)
        dueDate.setDate(dueDate.getDate() + 15)

        await prisma.invoice.create({
          data: {
            clientId: client.id,
            invoiceNumber,
            amount,
            vatAmount,
            totalAmount,
            billingPeriodStart: periodStart,
            billingPeriodEnd: periodEnd,
            dueDate,
            status: 'pending',
          },
        })

        results.generated++
      } catch (error) {
        console.error(`Error generating invoice for client ${client.id}:`, error)
        results.errors++
      }
    }

    // Log to audit
    await prisma.auditLog.create({
      data: {
        userId: 'system',
        userName: 'System',
        userEmail: 'system@oficio.app',
        userRole: 'SYSTEM',
        action: 'AUTO_GENERATE_INVOICES',
        actionCategory: 'INVOICE',
        entityType: 'invoice',
        changesSummary: `Auto-generated ${results.generated} invoices, skipped ${results.skipped}, errors ${results.errors}`,
      },
    })

    return NextResponse.json({ success: true, data: results })
  } catch (error) {
    console.error('Cron generate invoices error:', error)
    return NextResponse.json({ success: false, error: 'Internal server error' }, { status: 500 })
  }
}
